# Generated by Django 5.1.7 on 2025-03-18 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0002_farmer_farm_size_alter_farmer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='farm_size',
            new_name='Acres',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='duration',
            field=models.CharField(default=60, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seedling',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seedling',
            name='species',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='seedling',
            name='supplier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='trainer',
            field=models.CharField(max_length=255),
        ),
    ]
