# Generated by Django 5.1.7 on 2025-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society_App', '0004_donation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Acres',
            new_name='acres',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='email',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="If 'Money', enter amount in KES. If 'Seedlings', enter number of trees.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('Money', 'Money (KES)'), ('Seedlings', 'Seedlings (Number of Trees)'), ('Training', 'Training Sessions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Cash', 'Cash')], help_text='Only required if donating money.', max_length=20, null=True),
        ),
    ]
